### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by mocanew** [mariuscoto/wouso-new#46]
Trebuie stabilit daca vrem server-side rendering sau nu. E aproape imposibil de implementat daca vrem sa-l bagam la sfarsit.

- [MC] inca nu mi-e clar cum preiei variabile din backend in frontend, fara pug. Poti sa imi explici, te rog ?
- [VM] Clientul va face un request la server pentru informatii despre utilizator si le va cache-ui
- [MC] ok, hai sa o facem

**Comment by mocanew** [comment]
Nu cred ca intrebarea a primit un raspuns adecvat. 
Cand am spus server-side rendering, m-am referit la faptul ca poti randa orice rută din aplicatie, pe server, iar client-ul va primi tot html-ul necesar pentru first meaningful paint.

Personal, nu cred ca e nevoie de asa ceva, deoarece utilizatorii nostri au device-uri relativ noi (parsarea de JS pe aceste device-uri nu dureaza mult) si viteza la internet destul de mare (deci putem trimite bundle-uri relativ mari, rapid). Pe langa asta, continutul aplicatiei este dinamic si server-ul va fi "muncit" destul de mult.

**Comment by mocanew** [comment]
@neacsugeorge some input on this, please.

**Comment by mariuscoto** [comment]
De acord cu comentariul tau (si eu am citit issue-ul si m-am gandit la altceva). Cred ca cel mai bine este ca server-ul sa randeze "doar linia" de html care incarca JSul.
